### ISSUE TITLE
Version 2.0 Release Plan

### ISSUE THREAD

**Issue by jsoizo** [doyaaaaaken/kotlin-csv#149]
## Timeline

T.B.D.

## New Features

T.B.D.

## Breaking Changes

- [x] change namespace to `com.jsoizo`
- [ ] #157 

## Language and Tools version

- [x] KMP 2.1 #153 
- [x] Gradle 8.8 #154 
- [x] Bump up libraries #154 
- [x] change publish plugin supporting Maven Central Portal #155 
- [x] use kotlinx-kover for coverage report #153 
- [ ] use kotlin.test for unit testing (for support all runtime)
- [ ] Support more platforms

**Comment by vanniktech** [comment]
Is the library also split up into io bits & parsing bits? Such that we can finally use this library also in the Multiplatform context?

**Comment by jsoizo** [comment]
@vanniktech 

> split up into io bits & parsing bits

That looks very good. However, I plan to update the KMP version first before implementing support for each platform. We may change the design in the process.

**Comment by rajatsrma** [comment]
@jsoizo what is the potential timeline to release the updated kmp version ?

**Comment by jsoizo** [comment]
@rajatsrma I apologize for not avoiding time here as I am currently very busy with my day job.
I will try to take some time this summer, maybe in July, to improve this library and respond to pull requests.
I hope you can wait until then.

**Comment by nicolasf** [comment]
Hi @jsoizo.
Do you have plans on moving forward with this over the next few months?

Thanks!
